import './globals.css'
import { ReactNode } from 'react'
import { Navbar } from '@/components/Navbar'
// import { Footer } from '@/components/Footer'
import { Categorias } from '@/components/Categorias'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="flex">
          <Categorias />
          {children}
        </div>
      </body>
    </html>
  )
}
